name: JavaAnt
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Configurar y correr java+ant
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: cd AntJUnitTest && ls -r    
      - name: Build with Ant     
        run: ant -noinput -buildfile AntJUnitTest/build.xml
        #Guardar los resultados
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/jar
